# REST API

### Root Test
GET http://localhost:3000/

### About
GET http://localhost:3000/about

### Get All Profile
GET http://localhost:3000/profile

### Create New Profile
POST http://localhost:3000/profile
Content-Type: application/json

{
  "username": "demo1",
  "password": "1234",
  "mobile": "0933851532",
  "cardId": "1233857891235"
}

### Get Profile by ID
GET http://localhost:3000/profile/b00ad9b2-b9a3-49d6-a524-440bd5c3eb8e
